# Generated by Django 4.1.4 on 2023-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('price', models.FloatField(max_length=255)),
                ('model_number', models.CharField(max_length=120)),
                ('prodcut_url', models.URLField(blank=True, max_length=600, null=True)),
                ('product_image_url', models.URLField(blank=True, max_length=600, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, max_length=50, null=True)),
                ('categories', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
