# Generated by Django 4.1.4 on 2023-01-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheckapp', '0002_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
